### PR TITLE
140 refactor menuscene

### LINKED ISSUE #140: Refactor MenuScene
The menu has too many buttons and savegame loading is not really clear.
We must create a new/load gamescreen before we advance to the main menu.
In this screen we give the user the option to pick an existing savegame or to generate a new one with an input field.

This way, when you leave your game, you'll stay in your "account" when you go to the main menu. In that case you can buy new skins still logged in. 

This will also mean that you have to display the current user somewhere in the main menu.

- [ ] New login screen
- [ ] Stay logged in on menu
- [ ] Display user

< feature, user-interface

### PR DESCRIPTION
**Pull request by MathiasMeuleman**
Will close #140 

This features a complete refactoring of the MainMenuScene.
Also, the new AccountScene has been introduced.
This gives us a even better experience with the saving and loading of games.

<review

### CODE REVIEW

**Comment by mpsijm** [comment]
- In AccountScene, it shows the currently loaded file. This is not needed anymore, as you're "not logged in" when being in the AccountScene.
- In SettingsScene, the username Label messes up the entire layout.
- To be continued

**Comment by thervh70** [comment]
I agree with @mpsijm. Ive taken a good look at the functionality and i approve this.
Fix the points and merge away.

Also master conflicts with this branch.

< review

**Comment by MathiasMeuleman** [comment]
I fixed everything, please take another look and merge!

<review

**Comment by MKerkhof** [comment]
Everything looks great! This way of creating a user name or loading a game is way more logical. I fixed some last SAT warnings for you and will merge this if Travis is oke with it!

<review

**Pull request merged**
