### PR TITLE
194 delete savegames

### LINKED ISSUE #194: Delete button in AccountScene
Add an extra button in the AccountScene that enables the user to delete a certain save game entry.

< feature, user-interface

### PR DESCRIPTION
**Pull request by MathiasMeuleman**
Will close #194 

Added a button in AccountScene with which you can delete an account in-game.
Not much to review, just an extra button, some refactoring due to too a too large method and adaptions to the E2E

Please review!

<review, feature, user-interface

### CODE REVIEW

**Comment by thervh70** [comment]
Changes are looking good. 1 thing to add: the logger should be notified of this event. Deleting an account is certainly something the log should contain!

If that feature is added this is ready to be merged.

< review

**Comment by mpsijm** [comment]
I agree with Robin, creation, deletion and loading of accounts should all be logged :)
The button working really nice, so when the logging works, this can be merged! :)

<review, feature

**Comment by MathiasMeuleman** [comment]
The notifier is now also working for the delete button! Please re-review and merge :)

<review, organisation

**Comment by mpsijm** [comment]
Confirmed that it works :) Let's merge this thing, after you removed the empty class :)

<review, logic

**Comment by thervh70** [comment]
Yes, i agree with the new changes. @mpsijm and i have reviewed this small PR thoroughly. I'll merge this branch.

< review

**Pull request merged**
