### PR TITLE
93 Added multiple track parts

### LINKED ISSUE #93: Add diversity in track
- [x] Generate multiple text documents
- [x] Take care that the parts are parsed correctly

### PR DESCRIPTION
**Pull request by thervh70**
Will close #93

< feature

### CODE REVIEW

**Comment by thervh70** [comment]
Code review is not really necessary. Please use manual revision and tell me if you think the track is mixed enough.

**Comment by mpsijm** [comment]
I played, I liked :) Please merge!

**Comment by MKerkhof** [comment]
Looks good, makes the game way more fun. 

<review

**Comment by MathiasMeuleman** [comment]
I also tried! Looks fine, will merge :)

<review

**Pull request merged**
