### PR TITLE
168 create JAR for server

### LINKED ISSUE #168: Create JAR for server

### PR DESCRIPTION
**Pull request by mpsijm**
Will close #168 
!! New Pull Request, when #164/#170 was merged into master, the old PR auto-closed. !!

The main jar includes everything, literally everything.
The server jar excludes everything but the server package.
The server jar should be run from the command line with java -jar HighscoreServer.jar, else you won't see the console output.

<review, configuration

### CODE REVIEW

**Comment by MathiasMeuleman** [comment]
Please change the two buttons 'Fetch and Send' in Highscores to one 'Update' button. Users are stupid, take this in account when programming

<review

**Comment by mpsijm** [comment]
That has nothing to do with this issue. See #174.

<review,planning

**Comment by mdingjan** [comment]
Lookin' good! Checking SAT violations is not applicable.. :P 
Please merge!

<feature

**Comment by thervh70** [comment]
Will merge!

< review

**Pull request merged**
