### PR TITLE
115 exception logger

### LINKED ISSUE #115: Print Stacktrace to Logger instead of System.out

### PR DESCRIPTION
**Pull request by mpsijm**
Will close #115 

The logger now logs exceptions.
Please review! :)

<interface,documentation

### CODE REVIEW

**Comment by mdingjan** [comment]
Seems fine to me :) Didn't find any checkstyle warnings nor defects.
Ready for merge.

<review

**Comment by mpsijm** [comment]
I derped around for a bit, but this PR is still reviewable. Please do! :)

<review,bug

**Comment by MathiasMeuleman** [comment]
This looks fine! PMD is fixed now, code looks good, so plz merge :)

<review

**Comment by mdingjan** [comment]
I reviewed the changes; looks fine. (Still) Didn't find any violations nor defects. ;)
Ready for merge!

<review

**Comment by MathiasMeuleman** [comment]
1 + 1 = 2, will merge :)

<review

**Pull request merged**
