### PR TITLE
72 track

### LINKED ISSUE #72: Moving of track
- [ ] Build trackpiece class
- [ ] Link to GUI
- [ ] Link to step (in order to accelerate)
- [ ] Take care of textures

### PR DESCRIPTION
**Pull request by thervh70**
Will close #72.

This PR gives the track new functionality.
It ensures the track will move and that the track is added and deleted when needed.

It impacts the performance of the game, so please review the performance and tell me whether i could improve this.

< feature

### CODE REVIEW

**Comment by MathiasMeuleman** [comment]
This looks great! Game has become a lot more realistic
I did not run into any performance issues, so good job!

Please merge

<review

**Comment by mpsijm** [comment]
Only PMD warnings I could find: in the Light, Track and Wall renderers, at lines 60, 57 and 59 respectively, there is a double lightDepth/trackDepth/wallDepth that could be declared final.

It looks amazing indeed, however, I do have performance issues. And I know my PC is not as fast as the one you guys have, but it's at least a decent laptop that *should* be able to run our game smoothly.
Maybe you can take another look at the performance, @thervh70 ?

<review, performance, layout

**Comment by mdingjan** [comment]
I just reviewed your changes. The lights look really fancy in the scene! :D
As Maarten already mentioned, there are still 3 PMD warnings left. Please fix them.
I didn't find any other warnings with our SAT.
Besides, I'm running in performance issues as well.. Please try to find the cause of it.

<review,performance

**Comment by MKerkhof** [comment]
Didn't have any performance issues on my laptop so decided to check on my desktop that is slightly less powerful and got the same result as mentioned above: Not much lag, but every now and then a few seconds. I think this should be fixed before merging.

<review

**Comment by mpsijm** [comment]
I fixed the performance issues for you. If you merge master first, and make sure there is no trace of any SAT warning at all, this branch is ready to be merged :D 

<review, performance

**Comment by MKerkhof** [comment]
Looks great, performance issues are indeed fixed! Everything runs smooth again. Ready to be merged in my opinion!

<review

**Comment by MathiasMeuleman** [comment]
Still no performance issues at my pc.
As soon as Travis passes I will merge

<review

**Pull request merged**
