### PR TITLE
4 lanes

### LINKED ISSUE #4: Lanes
- [x] Character must start in middle lane
- [x] Multiple lanes must be present
- [x] Character must be able to change lanes
- [x] Character cannot run out of lanes

### PR DESCRIPTION
**Pull request by MathiasMeuleman**
Will close #4 

All back-end code for player movement (left and right) is present. Frame for jump and slide is also available. Unit tests for movement are done, manual testing is not yet possible cause KeyListener requires a GUI.

### CODE REVIEW

**Comment by thervh70** [comment]
@MathiasMeuleman please review all the warnings generated by Checkstyle

**Comment by thervh70** [comment]
@MathiasMeuleman ive merged the new master in for you

If you finish the checkstyle errors and others review this branch too we can merge it.
In that case it is time to tag it with version 0.2

**Comment by MKerkhof** [comment]
Looks good, couple of checkstyle errors left like what Robin said. If that's fixed, then it is ready to be merged in my opinion.

**Comment by mpsijm** [comment]
As Mathias is out for the weekend, I fixed his Checkstyle warnings. My IDE gives no warnings anymore, but do not hesitate to check for yourself for any warnings!
In my opinion, this PR is ready to be merged, though I would like to see a small test for KeyMap (because of the if != null branch) to increase coverage. This has no priority at the moment though.

**Comment by mdingjan** [comment]
I just reviewed #4. I fixed the two last Checkstyle warnings and committed my changes.
In my opinion this branch is ready to be closed now. 
(But as Maarten said, keep the KeyMap test in mind :) )

**Comment by MathiasMeuleman** [comment]
So this branch is ready to be merged I guess. Can someone please do so?

**Pull request merged**
