### PR TITLE
152 bugfix

### LINKED ISSUE #152: Bug: invulnerability
If a game is exited while the powerup is active, you will keep this powerup in a restart.

### PR DESCRIPTION
**Pull request by thervh70**
Will close #152

This branch features a bugfix: for the powerup reset after a return to the main menu and reload.

Also it has a small refactor for the cheat mechanism.

< bug

### CODE REVIEW

**Comment by mpsijm** [comment]
Thanks for fixing this, it works nicely :) Bug has been fixed, looking nice, ready to be merged!

<review, bug

**Comment by mpsijm** [comment]
Okay, one PMD thing:

    private static boolean cheat = false;

Doesn't have to be initialized to false, as it defaults to false.
Also, this field has the same name as the method. You might consider renaming it.

<naming,logic,review

**Comment by MKerkhof** [comment]
Looks good, as it is not a big PR and just a minor fix, I will merge it right away :)

<review

**Comment by MKerkhof** [comment]
Note to self, closing != merging. 

<oops, review

**Pull request merged**
