### PR TITLE
99 Static Analysis Tools review

### LINKED ISSUE #99: Static Analysis Tools review
The three SATs for our projects should be reviews.
There are some rules in these tools which are not needed for our projects.
Some rules should be removed, others should just stay and its warnings should be fixed.
Tools:
- [ ] Checkstyle
- [ ] PMD
- [ ] FindBugs

### PR DESCRIPTION
**Pull request by mpsijm**
Will close #99 

Everything is tidied up now, and by that I mean REALLY tidy. If anyone dares to make a mess ever again... Better run!
- Pom has now two checkstyle configurations, which are almost duplicate. The only difference is that the rules for "main" force JavaDoc comments/styling and the rules for "test" don't.
- PMD Now has a config file with the rules that are really needed for our project.
- Currently, the only remaining violations are in `PopupMenu` and `e.printStackTrace()` in the Logger and TrackParser.

Have fun reviewing! :)

<configuration,layout,documentation,review

### CODE REVIEW

**Comment by MathiasMeuleman** [comment]
I have a few checkstyles for you!
Mainly 'not designed for extension'

Logger.gameupdate
Player.isInvincible
Player.setInvincible
Player.getMoveLane

And trailing spaces at

PopUpMenu (139:0)

<review

**Comment by mpsijm** [comment]
- I removed the "not designed for extension" rule, because it messes with our Mocking tests. If you think it's really needed for our project, please tell me why.
- I said in the description of the PR that indeed PopupMenu is not Checkstyled yet, because this is done in branch 92.

<review,configuration,layout

**Comment by MathiasMeuleman** [comment]
Oke, then this is ready to be merged :)

<review

**Comment by mdingjan** [comment]
Looks fine; couldn't find anymore checkstyle warnings nor insufficient Javadoc.
Besides, I really want the checkstyle extension in master :P
Ready for merge!

<review

**Comment by thervh70** [comment]
I've reviewed this branch and I agree: this is ready to be merged.

**Pull request merged**
