### PR TITLE
99 SAT review

### LINKED ISSUE #99: Static Analysis Tools review
The three SATs for our projects should be reviews.
There are some rules in these tools which are not needed for our projects.
Some rules should be removed, others should just stay and its warnings should be fixed.
Tools:
- [ ] Checkstyle
- [ ] PMD
- [ ] FindBugs

### PR DESCRIPTION
**Pull request by mpsijm**
Will close #99

Please, when reviewing, try to use the tools in your IDE. For some reason, nobody did this during the previous review.
Checkstyle and PMD should now work also in IntelliJ. 

<configuration

### CODE REVIEW

**Comment by MathiasMeuleman** [comment]
So which file do I take when I want to import PMD rules into IntelliJ?

<review, organisation

**Comment by mpsijm** [comment]
The .ruleset file should cover all the PMD rules. I have removed all Eclipse-specific rules, if I'm correct.
<review,configuration

**Comment by mdingjan** [comment]
All Static Analysis Tools work for me at the moment, all changes included.
For me, this branch is ready to be merged. But everyone must have done the same, before this branch is merged into master.

<review,logic

**Comment by MathiasMeuleman** [comment]
I just pushed a IntelliJ compatible PMD.xml, please use this if you are using IntelliJ.
Furthermore, I think this branch is ready to be merged!

<review

**Pull request merged**
