### PR TITLE
144 Refactor sound speedup

### LINKED ISSUE #144: Refactor sound speedup
The current sound speedup features only a part of the track in a discrete speedup.

Research has to be done whether we can improve this.

### PR DESCRIPTION
**Pull request by mdingjan**
Will close #144

The increase of the speed of the soundtrack is now continuously!

The soundtrack's speed is now updated based on the distance of the player on runtime. Every time a player increases it's distance by 50, the speed is increased by 0.01. These two numbers (50 and 0.01) are constants and can of course be changed. The implementation is there!

Please review and enjoy the music!

<feature

### CODE REVIEW

**Comment by mpsijm** [comment]
Looking good, sounding good! I fixed some things for you, in my opinion it's now ready to be merged!

<review,layout,performance

**Comment by thervh70** [comment]
The overall functionality is good, however i seem to hear a slight lag at every 50 meters. It is very frustrating. Please check if you can solve this.

< review

**Comment by mpsijm** [comment]
I already checked, and this cannot be solved. This problem lies in the MediaPlayer of JavaFX. Unless we write our own, or we switch to another one in these last 4 hours, this cannot be fixed, unfortunately. 

<review,user-interface

**Comment by MathiasMeuleman** [comment]
It is indeed the update of the score and coins that causes this. In my opinion this is good enough, if we want to fix this, that can also be done in a later iteration.

I believe this issue is finished, will merge!

<review

**Comment by mdingjan** [comment]
@thervh70: Indeed all of the above.
I can make the soundtrack increase less frequently, but that would be something for the next iteration, if needed.

<review,feature

**Pull request merged**
