### PR TITLE
174 highscores feedback/c gui improvements

### LINKED ISSUE #174: Resolve HighscoreServer feedback
Jurgen's feedback:

174a: naming and documentation
- [x] When launching a new server when the application is already open it says: exiting, but does not. Also throws an exception (in CLIThread) when finally closing it manually before ultimately being shut down.
- [x] Extending Thread is an anti-pattern. It’s better to create (or implement) a Runnable and run that in a new Thread. Nice read: http://stackoverflow.com/questions/541487/implements-
runnable-vs-extends-thread
- [x] Is there a reason to have 5 commands that shutdown the server, without having any different behavior?
- [x] Highscores#add has an if statement that is not needed. The block only passes the Boolean value of the equals. Redundant code.
- [x]  Highscore#parse Javadoc states that it parses any toStrong() method to a Highscore.
- [x] ServerSocket in HighscoreServer shouldn't be called `ss`

174b: parsing and testing
- [x] Nearly all of the classes manipulate Strings in some way to function properly. This is a bad design. It would be better to have some sort of ‘parser’ class that eats all the data that is received and digests them in Objects that your application can understand. Otherwise the scalability is greatly reduced.
- [x] Massive whitespace in console between different connects.
- [x] Testing communication (Unit test instead of Integration test , prevents test hanging)

174c: GUI improvements (to make it all more intuitive)
- [x] Sending highscores only works from the HighScores menu.
- [x] Highscores are overwritten, but cannot view my own top 10 highscores.
- [x] E2E should test HighscoreScene.

### PR DESCRIPTION
**Pull request by mpsijm**
Will (finally!) close #174 

~~Please merge #189 before this branch. I will resolve the merge conflicts after this.~~ Done.
Summary of changes:
- Added Highscore button in Death popup
- Send/Fetch buttons have been merged in one Update button
- Added a TabPane in HighscoreScene so you can switch between global and local highscores
- E2E now also tests the HighscoreScene

Have fun reviewing!

<review, testing, logic, user-interface

### CODE REVIEW

**Comment by mdingjan** [comment]
I've reviewed your changes. Lookin' very good! Test additions are nice as well.
In my opinion you've covered all feedback of Jurgen with this last PR. Good job! The feature has really improved. :)

The only thing I want to point out is that, as you know, this branch isn't really stable with respect to Travis' builds. Locally all tests work perfectly, but Travis doesn't always agree. It's not a big issue though, as we can rerun the builds, but it's a bit 'time consuming' :P.
I fixed the last Checkstyle violation, so this branch is ready for take-off in my opinion. ;)

<review,testing

**Comment by mdingjan** [comment]
Edit: Oh and please merge master ;P

<review

**Comment by mpsijm** [comment]
I have merged master, so one or two more reviews and this can be closed :)

<review

**Comment by MathiasMeuleman** [comment]
This is looking way better now :)
Maybe add a bit of explanatory text about the difference between local and global highscores? Is not clear yet. Furthermore, next person gets to merge!

<review

**Comment by thervh70** [comment]
I've taken a brief look at your changes and i like them.
Besides, the failing builds now arent present anymore.
I'll merge this branch.

< review

**Pull request merged**
