### PR TITLE
1.0.2 process feedback

### PR DESCRIPTION
**Pull request by mpsijm**
Ready for review!

Lots of warnings have been resolved, and the E2E will now remove obstacles and coins to ensure consistency in tests.
Travis will now cache Maven dependencies (this seems to reduce test time by about half a minute).
The near infinite amount of warnings generated by the non-3D-virtual-display has not yet been resolved.
Current test line coverage: 94.6% (35/653 lines missed).

Will result in version 1.0.2!

### CODE REVIEW

**Comment by MathiasMeuleman** [comment]
Looks nice! As soon as you fix your travis build you can merge!

**Comment by MKerkhof** [comment]
+1, seems ready to merge if, what Mathias said, Travis stops complaining :)

**Comment by mpsijm** [comment]
Travis is happy, if one more person looks at it (@mdingjan or @thervh70) they can merge it :)

**Comment by mdingjan** [comment]
A nice addition to the master :) Now that Travis is happy, I'm happy as well :)
Will merge.

**Pull request merged**
