### PR TITLE
178 powerup sound effects

### LINKED ISSUE #178: Add sound effects to the new powerups
If all powerups have been added, then new sound effects have to be added to those powerups. 
This may require a change in the handling of the current soundtrack in the GameScene (for example current soundtrack could be paused and sound effect has to be played and when finished this current soundtrack has to be resumed again).

<feature

### PR DESCRIPTION
**Pull request by mdingjan**
Will close #178 

I've implemented two sound effect:
- A chopping sound effect for chopping the logs while PowerupDestroy is active.
- A invulnerability sound effect for being invulnerable while PowerupInvulnerabile is active.

Please review!

<feature,review

### CODE REVIEW

**Comment by mpsijm** [comment]
Code is looking good, but I found a bug: catching an Invulnerable powerup multiple times will play the "soundeffect" multiple times, which is not what we want because it's music. Please fix, after that it's ready to be merged :)

<review, layout, logic, user-interface

**Comment by thervh70** [comment]
Looking good. I love the new mario references!
Please merge.

< review

**Comment by mdingjan** [comment]
Bug has been fixed, @mpsijm thanks :D 

<bug,feature

**Comment by mpsijm** [comment]
Okay, then I will merge this now :) and you're welcome :D

<review, feature, bug

**Pull request merged**
