### PR TITLE
68 event logger

### LINKED ISSUE #68: Event Logger
- The user shall be able to read a log file containing all events that have happened during the game.
  - The log shall have timestamps.
- Tasks for implementation:
  - [x] Make Game "observable"
  - [x] Make Logger class
  - [x] Make Logger observe Game
  - [x] Make Logger poop stuff to text file
    - [x] Button presses in Main Menu
    - [x] Game starts
    - [x] Player starts moving 
    - [x] Player stops moving
    - [x] Player jumps
    - [x] Player slides
    - [x] Player picks up coin
    - [x] Game is paused
    - [x] Game is continued
    - [x] Game is exited to Main Menu
    - [x] Player bumps into obstacle / Game ends
  - [x] Profit

### PR DESCRIPTION
**Pull request by mpsijm**
Will close #68 

Ready for review! :)

<feature

### CODE REVIEW

**Comment by MKerkhof** [comment]
Looks good, logger works great! Only thing remaining is quite a few checkstyle warnings, when those are fixed i'ts ready to be merged in my opinion.

<feature, documentation

**Comment by mpsijm** [comment]
My excuses by the way, two of my last commits have #70 in their commit title, while this should have been #68. Unfortunately this can't be changed. I'll try to take notice better in the future. 

<naming

**Comment by MathiasMeuleman** [comment]
As said, there are a number of checkstyle errors. Please fix them, then this is ready to be merged. +1

<feature, documentation, review

**Comment by MathiasMeuleman** [comment]
Much better now, please merge

<review

**Comment by mdingjan** [comment]
The logger works really good :) This branch is ready to be merged, in my opinion. ;)

Will merge.

<review

**Pull request merged**
