### PR TITLE
145 whitespace unification and package reordering

### LINKED ISSUE #145: Whitespace unification and package reordering
- [x] whitespace unification
- [x] package reordering

### PR DESCRIPTION
**Pull request by mpsijm**
Will close #145

Sorry for breaking `git blame`! If something is bugged somewhere, please checkout v1.3 to use `git blame`, as literally nearly all lines in all files have been changed xD
So, from now on: never use tab characters anymore, and when creating new classes, make sure you're in the right package :)
Not much functionality to review, this should be checked on layout very extensively!

<review,configuration,layout,organization

### CODE REVIEW

**Comment by MKerkhof** [comment]
Checkstyle complains about these two methods being public:
capture

Besides this, I really like the new structure! Seems way more logical do have it organized this way. In my opinion, it is ready to be merged if the checkstyle errors are resolved!

**Comment by MKerkhof** [comment]
Nice, everything seems oke now, ready to be merged if other people have reviewed it too.

<review

**Comment by thervh70** [comment]
The diff is ridiculously long, so there's no way to check whether all whitespaces have been correctly replaced.

However i can say this: you should also refactor the package structure of the resources in order to complete this reordering.

I repeat the message placed by @MKerkhof: ready to be merged if other people have reviewed it too.

< review, organisation

**Comment by mdingjan** [comment]
I went through all classes.. 
- All tabs seem to have disappeared.
- The new package reordering looks fine; it gives a better overview now.
So I think we can merge this branch.

Will merge!

<review,layout,organisation

**Pull request merged**
